### ISSUE TITLE
Support GPG keys (signing and git ssh authentication)

### ISSUE THREAD

**Issue by Just-Insane** [cdr/sshcode#104]
It would be nice to have support for SSH and GPG keys from the client. Ideally, this would be available in code-server directly, though without making the private keys available on the remote I don't think that it would be possible.

Since sshcode is making an ssh tunnel, we can use that to make the keys available via gpg agent forwarding, however, this requires some setup on the client and remote, which should probably be documented here.

**Comment by Just-Insane** [comment]
I was able to use these resources to get gpg-agent forwarding working, however, I am still having some issues where when trying to sign commits with my GPG keys.

1. https://github.com/drduh/YubiKey-Guide/issues/85#issuecomment-451710482

2. https://mlohr.com/gpg-agent-forwarding/

I am able to pull a private repository using ssh, however, when trying to make commits, I get an error from GPG that there was no secret key found to perform the encryption.

**Comment by roberthmiller** [comment]
Not sure if this is safe in any way. You should generate a new gpg and ssh key for your remote server for security reasons. It would be really awful to have to regenerate keys if your remote instance got into the wrong hands.

**Comment by Just-Insane** [comment]
> Not sure if this is safe in any way. You should generate a new gpg and ssh key for your remote server for security reasons. It would be really awful to have to regenerate keys if your remote instance got into the wrong hands.

I feel like there might have been some miscommunication. Using agent forwarding, the requests are handled by the gpg-agent on the client (my laptop), via the private key stored on my yubikey. Using sshcode, the code-server instance is only available to my laptop (via the ssh tunnel).

I feel like the setup for agent forwarding should be better documented.

**Comment by roberthmiller** [comment]
So, your thoughts for this would be the forward the ssh agent and gpg-agent to your remote instance for gpg signing and pushing to a git repo?

**Comment by Just-Insane** [comment]
That is correct. I've got the ssh part working correctly, and cloning a private repo from GitHub works.

The problem is, when trying to push changes to the repository, the options synced via settings sync also tell the remote instance to sign the commits. In theory, this should work, as I have copied the public keys and have forwarding working correctly (as far as I can tell), however, it fails to sign the commit, with GPG returning an error that there is no private key available.

**Comment by roberthmiller** [comment]
have you forwarded both agents via sshconfig?

**Comment by Just-Insane** [comment]
From what I can tell, the steps in those two links should forward both.

**Comment by deansheather** [comment]
I think that forwarding the GPG agent/SSH agent is outside of the scope of sshcode as both can be done through the sshconfig or `-ssh-flags`. If you're having issues with GPG agent forwarding, it's likely an ssh configuration issue, especially if you can't get it to work in a regular SSH session.
