### ISSUE TITLE
code-server is not being updated to the latest version

### ISSUE THREAD

**Issue by maxfi** [cdr/sshcode#105]
Using [`sshcode v0.7.0`](https://github.com/cdr/sshcode/releases/tag/v0.7.0) the logs show:

```
INFO  code-server v1.939-vsc1.33.1
```

The latest version of `code-server` at time of writing is [`1.1119-vsc1.33.1`](https://github.com/cdr/code-server/releases/tag/1.1119-vsc1.33.1). It appears that https://codesrv-ci.cdr.sh/latest-linux isn't updated with the latest release.

**Comment by roberthmiller** [comment]
This looks like it would have something to do with the `wget` command, but that has never changed.

**Comment by nathanpotter** [comment]
I was able to update the binary located at https://codesrv-ci.cdr.sh/latest-linux and validate that it's now up to date.

@sreya92 feel free to close this, I don't seem to have the correct repo perms at the moment

**Comment by maxfi** [comment]
@nathanpotter @sreya92 Does https://codesrv-ci.cdr.sh/latest-linux get updated automatically when a new `code-server` release is created? I'm still seeing:

```
INFO  code-server v1.939-vsc1.33.1
```

and the latest release is [`1.1156-vsc1.33.1`](https://github.com/cdr/code-server/releases/tag/1.1156-vsc1.33.1).

**Comment by deansheather** [comment]
`curl -I https://codesrv-ci.cdr.sh/latest-linux` reports last-modified in May, even though the latest release was only 12 days ago.

Maybe this is a caching issue? Looks like we have Cloudflare active on cdr.sh.

**Comment by roberthmiller** [comment]
If so, then maybe we should add invalidate during deployment via a script?

**Comment by nathanpotter** [comment]
Just updated this to the latest code-server version. It doesn't get updated automatically yet

**Comment by kristianmitk** [comment]
@nathanpotter is there any information on when to expect this to be updated automatically?

**Comment by nathanpotter** [comment]
This looks done, just pulled it down and it's on code-server version `2.1692-vsc1.39.2`
It's automatically uploaded by code-server CI, see here:
https://github.com/cdr/code-server/blob/4e6f6bc2cc9f6579414835b16d54ac4261fda681/.travis.yml#L30

@sreya92 plz close

**Comment by kristianmitk** [comment]
@nathanpotter Thanks for the quick reply! But shouldn't it be then rather on `2.1698-vsc1.41.1`?

**Comment by nathanpotter** [comment]
It looks like the repo tag was changed for that release to remove the `-vsc*` suffix which may have broken the release upload. This appears to be an issue with the `code-server` repo though

**Comment by nathanpotter** [comment]
superseded by #167
