### ISSUE TITLE
Wrong version output

### ISSUE THREAD

**Issue by maxfi** [cdr/sshcode#106]
Using https://github.com/cdr/sshcode/releases/download/v0.7.0/sshcode-darwin-amd64.tar:

```
~ ./sshcode --version
v0.6.0-10-gdd4825b
```

This is the wrong version.

**Comment by badaz** [comment]
I noticed that too, I allso noticed that if you install sshcode with go you seem to get the latest version since it installs the server in a user local dir instead of /tmp. However sshcode --version now returns an empty string

**Comment by roberthmiller** [comment]
@ammario Can you run ci/build.sh again and update the release?

**Comment by ammario** [comment]
@badaz that is because we use build flags to specify the version. There's not a clean solution other than requiring everyone to `go install`/`go build` with that flag.

**Comment by ammario** [comment]
Tagged version v0.8.0 and retroactively fixed v0.7.0
