### ISSUE TITLE
--bind flag syntax

### ISSUE THREAD

**Issue by pgcudahy** [cdr/sshcode#110]
Just upgraded to 0.8.0 and really appreciate the rapid progress. One thing that confuses me is why the new `--bind` flag requires a url and port combination if it's only intended for local binding. Is anyone using a url other than 0.0.0.0 / 127.0.0.1? I expected the flag to only need a port, eg `--bind 10001` but that gives a fairly cryptic error of `FATAL	error: failed to parse bind address: address 10001: missing port in address`. Can either the documentation be updated to indicate that a url:port combination is expected, or drop the requirement for a url?

**Comment by roberthmiller** [comment]
Hey!

I just reviewed the code and it looks like what you are looking for is `:10001`. By default, the host is `127.0.0.1` and will always be the host if you only specify the port in this format: `:${port}`.

**Comment by deansheather** [comment]
Perhaps a change to the flag description describing this syntax would be a good idea.
