### ISSUE TITLE
Mac to Linux with MS C++ extension: missing binary

### ISSUE THREAD

**Issue by sbyma** [cdr/sshcode#112]
When using sshcode from mac to a linux server, the MS C/C++ extension fails and reports a missing binary. 

Error: Missing binary at /home/<user>/.local/share/code-server/extensions/ms-vscode.cpptools-0.23.1/bin/Microsoft.VSCode.CPP.Extension.linux

Obviously this is probably because the binary rsync'd from the mac won't run on the linux machine or isnt named correctly or something. Is there a way to get sshcode to fresh install an extension on start, rather than rsync it from the user's machine? 

I would imagine there are other architecture-specific extensions that may have this problem as well.

**Comment by deansheather** [comment]
There's no way currently to ask sshcode to install a specific extension on start and not rsync it currently. For your specific case, you might be able to just copy the file listed from a Linux installation of the extension to your Mac so it gets synced up next time.

In the future, we could implement an "ignore extension" repeatable flag that we pass to rsync.

**Comment by sbyma** [comment]
Alright. Currently working around by reinstalling the extension after the session is open, and then reconnecting with `--skipsync`
