### ISSUE TITLE
Feature Request: Use local Internet access and SSH to get all necessary files to remote server

### ISSUE THREAD

**Issue by magic-lantern** [cdr/sshcode#117]
My remote server I do development on has no outbound Internet due to security restrictions. My local machine however, does have access to the public Internet.

I'd like to propose a feature request to add a flag or option that allows for all necessary files to be downloaded via my local machine's Internet access, and pushed to the remove server via SSH. All necessary installations could then occur on the remote server.

If this is already a feature and I just haven't read or found the documentation, please let me know!

**Comment by deansheather** [comment]
What exactly do you mean by all necessary files? Do you mean copying your source code to the remote server? At the moment, this isn't supported but it would make for a great feature.

**Comment by magic-lantern** [comment]
I do not mean my source code files.

What I meant was all files required to install and configure [code-server](https://github.com/cdr/code-server). 

`sshcode` works great on a remote server that has access to the Internet; on a server with Internet blocked, it does not work. Hopefully the necessary files for installation and configuration could be downloaded locally and moved over via ssh.

**Comment by deansheather** [comment]
I think people using remote servers without a direct internet connection is a pretty limited usecase. Maybe we could add a `--no-update` flag that prevents the update check, so you could copy code-server to the machine yourself beforehand.

**Comment by deansheather** [comment]
Actually, closing this as it's a duplicate of #73.

**Comment by magic-lantern** [comment]
Thanks for helping to find a pre-existing feature request that covers this. I'll add some comments to that and follow it.
