### ISSUE TITLE
Reuse of cached code-server

### ISSUE THREAD

**Issue by changliao1025** [cdr/sshcode#131]
Does the sshcode install and run the code-server every time it was called?
Can it use cached code-server so it doesn't need to be reinstalled again?

**Comment by deansheather** [comment]
The code-server binary is cached on the remote server. Every time the script starts, it will contact our CI server to check if there's a newer version. If there isn't a newer version, the binary will be reused.

**Comment by Merith-TK** [comment]
Something happened when i merged this with my code and it... it cucked mine even more

**Comment by deansheather** [comment]
Did you comment on the wrong thing? @Merith-TK

**Comment by Merith-TK** [comment]
Yep....
But my worries are still there, I hit the merge button and uhm... Help?

**Comment by deansheather** [comment]
If you're having problems with your PR, please ask for help in the comments on your PR unless this issue is related.
