### ISSUE TITLE
Compress tarball with gzip

### ISSUE THREAD

**Issue by grhbit** [cdr/sshcode#142]
https://github.com/cdr/sshcode/blob/7e6845d1bda59a90b09f90b8fc7815cdc23267c5/ci/build.sh#L13-L14

Why not add an option `z` to compress for gzip?

Like this
```sh
tarname=sshcode-$GOOS-$GOARCH.tar.gz
tar -czf $tarname sshcode 
```

**Comment by deansheather** [comment]
Sounds good to me, cdr/sail does this already. Feel free to create a PR for this.
