### ISSUE TITLE
Chrome App Window does not work

### ISSUE THREAD

**Issue by Merith-TK** [cdr/sshcode#146]
as this states, I am not too sure of this is my fork, but something has caused it to stop opening a chrome app window. 

It used to do it just fine in the current repo state, but now it's not, I believe it may be possible that chrome has changed its flags

**Comment by Merith-TK** [comment]
This does not appear to be the case, I ran chrome by hand with the flags needed and it opened just fine as it should,

**Comment by deansheather** [comment]
This is only related to your fork so I'm closing this issue. Please track it in your PR comments or on your fork.
