### ISSUE TITLE
Compatibility with VSCodium?

### ISSUE THREAD

**Issue by pierrehenrymuller** [cdr/sshcode#149]
Hi,
I'm trying to work with VSCodium in opposate of VSCode not FLOSS. In VSCode OSS there is no Remote SSH plugin available (closed source) and sshcode is interesting to launch remote VSCodium but they don't work.

I thought it was the binary path that wasn't good. I made a symbolic link from codium to /usr/bin/code without success.

``` 2019-10-31 19:33:24 INFO	synced extensions in 1.339407986s
2019-10-31 19:33:24 INFO	starting code-server...
2019-10-31 19:33:24 INFO	Tunneling remote port 20119 to 127.0.0.1:38228
Option 'allow-http' is unknown. Ignoring.
Option 'allow-http' is unknown. Ignoring.
info  Server listening on http://127.0.0.1:20119
info    - Password is 4db1819bd2d1d4d3d45b5cbc
info      - To use your own password, set the PASSWORD environment variable
info      - To disable use --auth none
info    - Not serving HTTPS
2019-10-31 19:33:39 ERROR	failed to send SIGTERM to SSH master process: os: process already finished
                                                                                                          2019-10-31 19:33:39 FATAL	error: code-server didn't start in time: context deadline exceeded
```
I have verified, on target is listen to 38228 and localhost have 20119 listen for ssh process.
I have this informations on my Linux Debian 10 terminal when I launch sshcode on target with bastion host with latest sshcode version.

Do you have any idea?

**Comment by Merith-TK** [comment]
The err has nothing to do with vscodium, The only problems you should run into while using vscodium is the directories where vscode data is stored, you can set those with ENV variables, (dont know what, try `sshcode --help`)

Also those ports arnt having issues, 
What it does, is it runs code-server on the target, and gives it a random port to run on,

it will then tunnel that port over ssh to a random port on your client, and then attempt to open your browser to this new URL,

ssh > remote > open code-server on random port > Tunnel Port over SSH to random port on client >  open Browser to `127.0.0.1:RandomPort`

if those open ports are occupied by SSH, it cant use those.

**Comment by nhooyr** [comment]
Closing as this has been inactive for a long time and I believe @Merith-TK covered it.
