### ISSUE TITLE
sshCmdStr should be updated

### ISSUE THREAD

**Issue by Merith-TK** [cdr/sshcode#155]
as stated,
this line
https://github.com/cdr/sshcode/blob/master/sshcode.go#L147
```go
	sshCmdStr :=
		fmt.Sprintf("ssh -tt -q -L %v:localhost:%v %v %v 'cd %v; %v --host 127.0.0.1 --auth none --port=%v'",
			o.bindAddr, o.remotePort, o.sshFlags, host, dir, codeServerPath, o.remotePort,
		)
```
should be 
```go
	sshCmdStr :=
		fmt.Sprintf("ssh -tt -q -L %v:localhost:%v %v %v '%v --host 127.0.0.1 --auth none --port=%v %v'",
			o.bindAddr, o.remotePort, o.sshFlags, host, codeServerPath, o.remotePort, dir,
		)
``` 

as code-server is no longer opening (atleast for me) in the users PWD when they call it

This edit tells code-server to open that path DIRECTLY from code-server
same concept as upstream vscode

I have already implemented this in my fork (not yet pushed as i am still fixing it up)

**Comment by deansheather** [comment]
This patch doesn't work as you'd expect as code-server always opens the last opened dir before it tries to open whatever was passed on the command line. cdr/code-server#1132

**Comment by Merith-TK** [comment]
Okay this resolves it for code-server, but i was linked back here on sshcode, that resolves code-server, not sshcode. 

Working on an idea to get 3.0.2 working on sshcode
