### ISSUE TITLE
[BUG] [MINOR] sshcode-server opens previous directory instead of specified directory on new session

### ISSUE THREAD

**Issue by Merith-TK** [cdr/sshcode#156]
`sshcode developer@archlinux ~/Workspace` will open `~/Workspace`
When i come back later and choose to open `/opt/Workspace` 
`sshcode developer@archlinux /opt/Workspace` it will choose to open `~/Workspace` instead, 

the only fix i have for this, is changing something in settings.json, but that is not a good idea as it may sync back and mess up someones actual config on their personal PC
EDIT: Reworded beginning

**Comment by Merith-TK** [comment]
I am giving this a bump as this is kinda a big deal

**Comment by deansheather** [comment]
Dupe of #155
