### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by LucaGerlich** [cdr/sshcode#165]
sshcode crashes immediately after start. Im trying to run it on a remote Server with ubuntu 18.04. I'm sorry if thats a dumb question but i'm a total nooby.

`./sshcode root@xx.xxx.xxxxxx:xxxx
2020-02-21 01:46:11 INFO        starting SSH master connection...
2020-02-21 01:46:12 ERROR       failed to start SSH master connection: SSH master wasn't ready on time: SSH master process is not running
2020-02-21 01:46:12 INFO        ensuring code-server is updated...
ssh: Could not resolve hostname xx.xxx.xxx.xxx:xxxx: Name or service not known
2020-02-21 01:46:12 FATAL       error: failed to update code-server:
---ssh cmd---
ssh  root@xx.xxx.xxx.xxx:xxxx '/usr/bin/env bash -l'
---download script---
set -euxo pipefail || exit 1

[ "$(uname -m)" != "x86_64" ] && echo "Unsupported server architecture $(uname -m). code-server only has releases for x86_64 systems." && exit 1 
pkill -f ~/.cache/sshcode/sshcode-server || true
mkdir -p ~/.local/share/code-server ~/.cache/sshcode
cd ~/.cache/sshcode
curlflags="-o latest-linux"
if [ -f latest-linux ]; then
        curlflags="$curlflags -z latest-linux"
fi
curl $curlflags https://codesrv-ci.cdr.sh/latest-linux
[ -f ~/.cache/sshcode/sshcode-server ] && rm ~/.cache/sshcode/sshcode-server
ln latest-linux ~/.cache/sshcode/sshcode-server
chmod +x ~/.cache/sshcode/sshcode-server: exit status 255`

**Comment by joshpetit** [comment]
Did you find your fix? If so could you post it, I'm getting the same error.

**Comment by Merith-TK** [comment]
What is your host OS? the client?

**Comment by joshpetit** [comment]
Host OS is Ubuntu 18.04 x86_64, client OS is ubuntu 20.04 x86_64.

**Comment by Merith-TK** [comment]
what is the  error you are getting? can you pose in a codeblock?

**Comment by joshpetit** [comment]
`2020-04-27 07:49:39 INFO	starting SSH master connection...
2020-04-27 07:49:40 ERROR	failed to start SSH master connection: SSH master wasn't ready on time: SSH master process is not running
2020-04-27 07:49:40 INFO	ensuring code-server is updated...
ssh: Could not resolve hostname 192.168.1.72:39431: Name or service not known
2020-04-27 07:49:40 FATAL	error: failed to update code-server:
---ssh cmd---
ssh  192.168.1.72:39431 '/usr/bin/env bash -l'
---download script---
set -euxo pipefail || exit 1

[ "$(uname -m)" != "x86_64" ] && echo "Unsupported server architecture $(uname -m). code-server only has releases for x86_64 systems." && exit 1
pkill -f ~/.cache/sshcode/sshcode-server || true
mkdir -p ~/.local/share/code-server ~/.cache/sshcode
cd ~/.cache/sshcode
curlflags="-o latest-linux"
if [ -f latest-linux ]; then
	curlflags="$curlflags -z latest-linux"
fi
curl $curlflags https://codesrv-ci.cdr.sh/latest-linux
[ -f ~/.cache/sshcode/sshcode-server ] && rm ~/.cache/sshcode/sshcode-server
ln latest-linux ~/.cache/sshcode/sshcode-server
chmod +x ~/.cache/sshcode/sshcode-server: exit status 255
`

**Comment by Merith-TK** [comment]
Could be because it's trying to use the latest code-server which doesnt
support this... Try using the `--code-server-path` to point to a
code-server 2 release
