### ISSUE TITLE
Domain `cdr.sh` expired

### ISSUE THREAD

**Issue by cshuaimin** [cdr/sshcode#169]
Hi, I got this error when trying `sshcode`:

```
/root/.cache/sshcode/sshcode-server: line 1: syntax error near unexpected token `<'
/root/.cache/sshcode/sshcode-server: line 1: `<!DOCTYPE html>...
```

It seems that because the domain name has expired, `sshcode` just downloaded an HTML page.

**Comment by kylecarbs** [comment]
Fixing now, sorry for this silly issue.

**Comment by kylecarbs** [comment]
Should be fixed! Sorry about that.
