### ISSUE TITLE
Add support for GCP instances

### ISSUE THREAD

**Issue by kylecarbs** [cdr/sshcode#2]
```bash
sshcode gcp:test-kyle
```
We would execute `gcloud compute ssh test-kyle -- <ssh flags>` instead of the normal SSH command.

**Comment by Toeplitz** [comment]
Is there a work around to get this working at the moment?

**Comment by TimothyCole** [comment]
@Toeplitz gcloud should create a key in your .ssh folder if I recall correctly. You can use that key to connect with ssh flags `sshcode --ssh-flags "-i ~/.ssh/google_compute_engine" tim@123.456.789`
