### ISSUE TITLE
Ability to edit browser preference

### ISSUE THREAD

**Issue by coadler** [cdr/sshcode#35]
Currently if you have both google chrome and chromium installed, it will always pick google chrome. There should be a way to edit the order it checks or specify a browser.

**Comment by coadler** [comment]
On the flip side, does this really matter? Since it's in an app window you might not really notice the difference

**Comment by kylecarbs** [comment]
It could be annoying for an OS (like MacOS) that display running apps on a bottom-bar.

**Comment by nhooyr** [comment]
@kylecarbs could you expand, not sure what you mean

I think its fine to always use google chrome first and then fall back to the os specific stuff like `xdg-open` and `open` (I think that's how it works right now)

**Comment by ammario** [comment]
@coadler is this something that is hurting your workflow or you think it will hurt others?

**Comment by coadler** [comment]
This isn't hurting my specific workflow, but I could see a case where a user has both chrome and firefox installed but wants `sshcode` to use firefox. This was more of an issue when we were handling firefox manually instead of through `xdg-open`, but now chrome is the only browser we're using the app window with, so it might just make sense to transparently force chrome if installed since it gives the better experience

**Comment by nhooyr** [comment]
Yea this is fair but given no one has commented on it, I think everyone's fine with using Chrome.

**Comment by Merith-TK** [comment]
if it comes down to it, add a fork that checks a Environment variable to determine what to launch.

Currently working on a fork that uses firefox. only problem is that for some reason not all firefox releases have the `--ssb` flag or the `browser.ssb.enabled` bool var in `about:config` (and those that do, have it disabled by default)
![](https://i.imgur.com/Ph1BLPE.png) in this image i am using firefox dev edition and it works well, im just having a problem in my fork of actually running it
