### ISSUE TITLE
bind to address on eth0 in ChromeOS

### ISSUE THREAD

**Issue by ammario** [cdr/sshcode#54]

**Comment by roberthmiller** [comment]
does #82 solve this? It would just require chrome users to bind to `0.0.0.0` all the time instead of doing it by default. Should this be automatically detected and changed?

**Comment by sr229** [comment]
Keep in mind the eth0 address in CrOS for Crostini is at `penguin.linux.test` CrOS should handle the resolution properly

**Comment by roberthmiller** [comment]
I think that the bind option solves this. @sreya92, thoughts?

**Comment by sreya92** [comment]
Yup should work fine

**Comment by sreya92** [comment]
closed by #82
