### ISSUE TITLE
Dowload file or directory

### ISSUE THREAD

**Issue by vict0rsch** [cdr/sshcode#60]
Would it be possible to add a `Download` option to the context menu to download a file or directory to the local machine?

Would be super useful to do it from vscode rather than from some ftp client

**Comment by sreya92** [comment]
You want this added to `coder-server` not `sshcode` correct? If so I'd open up an issue against the `code-server repo` https://github.com/cdr/sshcode.git

**Comment by vict0rsch** [comment]
Indeed, my bad. Existing request on `code-server`: [#233](https://github.com/cdr/code-server/issues/233)
