### ISSUE TITLE
wget ERROR 403: Forbidden

### ISSUE THREAD

**Issue by jaykovski** [cdr/sshcode#66]
Getting 403 error while downloading code-server on Ubuntu 18.04, no extra config in wgetrc

```2019-04-26 18:13:56 INFO	ensuring code-server is updated...
+ mkdir -p /root/.local/share/code-server
+ cd /tmp
+ wget -N https://codesrv-ci.cdr.sh/latest-linux
--2019-04-26 17:13:57--  https://codesrv-ci.cdr.sh/latest-linux
Resolving codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)... 104.27.133.26, 104.27.132.26, 2606:4700:30::681b:841a, ...
Connecting to codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)|104.27.133.26|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-04-26 17:13:57 ERROR 403: Forbidden.

2019-04-26 18:13:57 FATAL	failed to update code-server: exit status 8
---ssh cmd---
ssh  root@1.2.3.4.5 /bin/bash
---download script---
set -euxo pipefail || exit 1

mkdir -p ~/.local/share/code-server
cd /tmp
wget -N https://codesrv-ci.cdr.sh/latest-linux
[ -f /tmp/codessh-code-server ] && rm /tmp/codessh-code-server
ln latest-linux /tmp/codessh-code-server
chmod +x /tmp/codessh-code-server```

**Comment by jaykovski** [comment]
Looks like for some reason my cloud server IP is blocked by cloudflare, I created new one in different location and it works

**Comment by DoyleRules** [comment]
What exactly did you do to fix this? I'm getting the following error:

```
2019-05-02 09:53:12 FATAL       failed to update code-server: exit status 255
---ssh cmd---
ssh  butler /bin/bash
---download script---
set -euxo pipefail || exit 1

mkdir -p ~/.local/share/code-server
cd /tmp
wget -N https://codesrv-ci.cdr.sh/latest-linux
[ -f /tmp/codessh-code-server ] && rm /tmp/codessh-code-server
ln latest-linux /tmp/codessh-code-server
chmod +x /tmp/codessh-code-server
```

**Comment by jaykovski** [comment]
> What exactly did you do to fix this? I'm getting the following error:
> 
> ```
> 2019-05-02 09:53:12 FATAL       failed to update code-server: exit status 255
> ---ssh cmd---
> ssh  butler /bin/bash
> ---download script---
> set -euxo pipefail || exit 1
> 
> mkdir -p ~/.local/share/code-server
> cd /tmp
> wget -N https://codesrv-ci.cdr.sh/latest-linux
> [ -f /tmp/codessh-code-server ] && rm /tmp/codessh-code-server
> ln latest-linux /tmp/codessh-code-server
> chmod +x /tmp/codessh-code-server
> ```

I changed the server IP address.
Yours is something different, what output you get before: FATAL exit status 255 ?
