### ISSUE TITLE
go get -u...  doesn't work in ubuntu

### ISSUE THREAD

**Issue by woshilrd** [cdr/sshcode#71]
I excuted  'go get -u go.coder.com/sshcode '， sys returned as below. 

 package golang.org/x/xerrors: unrecognized import path "golang.org/x/xerrors" (https fetch: Get https://golang.org/x/xerrors?go-get=1: dial tcp 216.239.37.1:443: connect: connection refused)

**Comment by ammario** [comment]
This seems like it might be a temporary issue with `golang.org`. Could you try it again?

**Comment by andrewsav-datacom** [comment]
Also on Ububtu I'm getting the following after running `go get -u go.coder.com/sshcode`:

```
# strings
/usr/local/go/src/strings/strings_decl.go:8:6: IndexByte redeclared in this block
        previous declaration at /usr/local/go/src/strings/strings.go:150:34
# bytes
/usr/local/go/src/bytes/bytes_decl.go:10:6: IndexByte redeclared in this block
        previous declaration at /usr/local/go/src/bytes/bytes.go:101:34
/usr/local/go/src/bytes/bytes_decl.go:17:6: Equal redeclared in this block
        previous declaration at /usr/local/go/src/bytes/bytes.go:18:25
/usr/local/go/src/bytes/bytes_decl.go:24:6: Compare redeclared in this block
        previous declaration at /usr/local/go/src/bytes/bytes.go:37:27
# crypto/cipher
/usr/local/go/src/crypto/cipher/xor_amd64.go:9:6: xorBytes redeclared in this block
        previous declaration at /usr/local/go/src/crypto/cipher/xor.go:58:33
/usr/local/go/src/crypto/cipher/xor_amd64.go:22:6: xorWords redeclared in this block
        previous declaration at /usr/local/go/src/crypto/cipher/xor.go:83:27
# crypto/rc4
/usr/local/go/src/crypto/rc4/rc4_asm.go:15:18: (*Cipher).XORKeyStream redeclared in this block
        previous declaration at /usr/local/go/src/crypto/rc4/rc4.go:61:6
```

**Comment by ammario** [comment]
Looks like your Go installation was overwritten incorrectly. Try deleting /usr/local/go and reinstalling.

**Comment by AndrewSav** [comment]
yeah, that worked, thanks. I wonder what overwrote it... may be you require a certain version of go?

**Comment by ammario** [comment]
There's no way this tool could overwrite it :man_shrugging:

**Comment by sreya92** [comment]
Seems like your issue is resolved, please reopen if you encounter more issues but like @ammario said it's not possible for the tool to overwrite your go installation
