### ISSUE TITLE
Option to upload code-server binary

### ISSUE THREAD

**Issue by kjetilhp** [cdr/sshcode#73]
Add option to upload code-server binary when there is no internet connection on the remote host.

**Comment by sreya92** [comment]
This is interesting, I imagine you would need this for cases where you have your entire machine firewalled except for the ssh port?

**Comment by kjetilhp** [comment]
Exactly :)

**Comment by roberthmiller** [comment]
`scp` would work for this. Using a ping to coder.com or something similar would be fine to check if egress traffic is allowed, then using the "client" (for lack of a better term) to download the code-server bin and scp it.

**Comment by deansheather** [comment]
I think people using remote servers without a direct internet connection is a pretty limited usecase. Maybe we could add a `--no-update` flag that prevents the update check, so you could copy code-server to the machine yourself beforehand.

**Comment by kjetilhp** [comment]
I think not, a lot of big organisations and certainly government institutions have a lot of in-house servers that never are allowed touching the internet. But a script with scp and no-update would do.

**Comment by magic-lantern** [comment]
I need this feature as well. In response to @deansheather comment about limited usefulness: I've worked in the healthcare industry for over 12 years.  Security is a key part of the software development lifecycle and IT portion of healthcare. I've worked for a large non-profit health care organization and an academic medical institution, and having open access to the internet is actually quite rare for any system with health care data. It's very common in health care to allow inbound connections such as SSH/RDP, but prevent outbound Internet access to reduce the likelihood of data exfiltration.

The other common case for security is that authentication at a web proxy is required to gain some outbound Internet access - which as previously mentioned is feature request #74

**Comment by deansheather** [comment]
Seems like I was wrong, maybe this would be a good idea after all.

**Comment by xgdgsc** [comment]
I also find this useful for my use cases in finance industry.

**Comment by deansheather** [comment]
Made a PR that adds a `--code-server-path` flag. You can specify a path to a local code-server binary and it will be uploaded instead of the update script being executed.

**Comment by deansheather** [comment]
The flag has been renamed to `--upload-code-server`, and has been merged into master. It should work with code-server v2 previews as well! :tada:
