### ISSUE TITLE
Add support for http_proxy at remote server

### ISSUE THREAD

**Issue by hoanghuynh** [cdr/sshcode#74]
My remote server needs to use an http_proxy/https_proxy to download packages from internet. Can you add support for this? Usually I would add `export http_proxy=someproxy:port` and `export https_proxy=someproxy:port` to the beginning of my script.

Even better, can we have an option to run some commands (like the `export`s above) before sshcode starts executing?

**Comment by sreya92** [comment]
This is similar to #73 ...would downloading it locally and scp'ing it to the server suffice? The only downside I see is that it could be potentially be quite slow depending on your network speed
