### ISSUE TITLE
Can't run on a server with multiple users

### ISSUE THREAD

**Issue by noook** [cdr/sshcode#76]
We currently cannot run the command on a server where other people are already using it. When running the script, it crashes at the moment it tries to delete `/tmp/sshcode-code-server` because it is owned by another user. We should be able to pass an option to define the name of our tmp folder, for exemple the same name suffixed by `/$USER`

**Comment by sreya92** [comment]
think this is a duplicate of #58 I should have this done soon

**Comment by sreya92** [comment]
@noook if you build the latest on master you should be good to go, I'm going to close this, feel free to reopen if you encounter problems
