### ISSUE TITLE
DNS option to use: 0.0.0.0

### ISSUE THREAD

**Issue by JamesGreenaway** [cdr/sshcode#78]
Is it possible for you to update sshcode so that it is not hardcoded to use 127.0.0.1 and give us the option to use 0.0.0.0. ChromeOS will not load anything except when it is forwarded to 0.0.0.0.

**Comment by roberthmiller** [comment]
I just skimmed the codebase and noticed that there are 2 places where `127.0.0.1` is hardcoded. Are you talking about the local machine or the remote?

**Comment by JamesGreenaway** [comment]
local machine.

**Comment by roberthmiller** [comment]
Ok. I can have a look into how to implement this and open a PR.

**Comment by JamesGreenaway** [comment]
great thanks!

**Comment by sreya92** [comment]
Is there a good way to detect that your in a ChromeOS environment?
