### ISSUE TITLE
HOWTO? use a TLS cert using sshcode?

### ISSUE THREAD

**Issue by xt0fer** [cdr/sshcode#83]
there are ways ot use TLS certs on coder, but what if I'm using sshcode? anyway to specify a cert to be used to secure the traffic?

**Comment by sreya92** [comment]
The traffic is secured by the ssh tunnel

**Comment by xt0fer** [comment]
ya know, that's what I thought. And perhaps I should have assumed that. I just saw what's below, and figured I ask...
` WARN No certificate specified. This could be insecure.`

**Comment by sreya92** [comment]
To elaborate, `coder-server` is running on `127.0.0.1` and we forward a port over SSH to your local machine. So there's no way anyone who is not on the actual remote instance could access your IDE. Forwarding the port over SSH and listening on the loopback device allows us to use the `--no-auth` flag without concern :)

**Comment by xt0fer** [comment]
And damn handy it is. I have fat old ATX box with a pretty fast i5 in the basement. This project gives it an entirely new lease on life. I can code on a machine that's pretty expensive to rent, from anywhere my cheap laptops take me...

**Comment by xt0fer** [comment]
you might also consider adding your elaboration to the sshcode README!
