### ISSUE TITLE
error: failed to parse host IP: host argument is not a valid IP address

### ISSUE THREAD

**Issue by magick93** [cdr/sshcode#84]
Hello

I've just installed sshcode, using `go get -u go.coder.com/sshcode`, and go to run it, and it fails with the below error:
```
sshcode myser@myserver.domain
2019-05-02 11:13:06 INFO	ensuring code-server is updated...
2019-05-02 11:13:06 FATAL	error: failed to parse host IP: host argument is not a valid IP address
```

Does it only work with ip addresses?

I'm running sshcode on Ubuntu 19.04.

**Comment by magick93** [comment]
I just tried with the IP address, rather than hostname, and get the same error.

**Comment by sreya92** [comment]
@magick93 try running `go get -u go.coder.com/sshcode` it should be fixed

**Comment by magick93** [comment]
Thanks @sreya92 - that solved that issue.
Now it fails with ` 2019-05-02 12:30:36 FATAL       error: code-server didn't start in time: context deadline exceeded `

**Comment by sreya92** [comment]
Hmm that's interesting, if instead you run `sshcode --ssh-flags='-l <user>' myserver.domain` does it work?

**Comment by sreya92** [comment]
Oh you know what, the previous instance of code-server was probably running, if you ssh into your server and do a `pkill codessh`, then run it again it should work. The tool should handle that case though, #24 I'll fix in a sec

**Comment by sreya92** [comment]
@magick93 I'm having a hard time recreating your issue, I was able to do it once but I was unable to recreate it, is this something you see consistently

**Comment by SscSPs** [comment]
@sreya92 try using the hosts saved in ~/.ssh/config file, i'm facing this issue as well

**Comment by sreya92** [comment]
@SscSPs could you post the error you're receiving?

**Comment by SscSPs** [comment]
@sreya92 I was facing that issue yesterday, but not anymore.
I was getting this one 
```2019-05-02 12:30:36 FATAL error: code-server didn't start in time: context deadline exceeded
```

**Comment by sreya92** [comment]
Gotcha yeah, it seems like like every once in a great while that can happen, simply retrying the command tends to work. I tried running the command 50 times and wasn't able to reproduce. Please reopen if you experience problems
