### ISSUE TITLE
Check if remote system is 32bit before downloading

### ISSUE THREAD

**Issue by coadler** [cdr/sshcode#92]
So we can give a decent error message since there aren't any code-server releases for 32bit systems

**Comment by roberthmiller** [comment]
`uname -m` will work for this, but not sure how to implement this without an initial connection before the code-server connection initializes.

**Comment by deansheather** [comment]
SSH(1) states that the exit status of `ssh` is the same as the exit status of the remote command. We could add an if condition to the download script that does `exit 1` if the output of `uname -m` isn't equal to `x86_64`.

**Comment by deansheather** [comment]
Made a PR for this check.
