### ISSUE TITLE
chromeos connection refused

### ISSUE THREAD

**Issue by ageisen2000** [cdr/sshcode#93]
Any way to make my web browser work with this? ChromeOS just gives me a connection refused error

**Comment by roberthmiller** [comment]
I am currently working on a fix for this. Re: #82

**Comment by roberthmiller** [comment]
Can you elaborate a little more? Is ChromeOS the remote host?

**Comment by roberthmiller** [comment]
Can you elaborate on this a little bit/

**Comment by ageisen2000** [comment]
When I install this on my ChromeOS crostini and fire it up using a remote server chrome will load up but I get a "connection refused" error

**Comment by ageisen2000** [comment]
Remote host is ubuntu 18.04

**Comment by roberthmiller** [comment]
ah, no problem. Once #82 is merged, you should be able to simply use the --bind argument.

**Comment by sreya92** [comment]
@ageisen2000 you can now specify `--bind=0.0.0.0:[<port>]` when you run sshcode to avoid this issue
