### ISSUE TITLE
specify port and don't bring up browser?

### ISSUE THREAD

**Issue by jots** [cdr/sshcode#95]
I'm using this from a crouton shell on a chromebook and sshing to a remote server.
When I start sshcode, it brings up the lynx browser.  How can I have it not bring up a browser, but instead print out the url it's running on? i.e. http://127.0.0.1:11428/  also how can I specify the port?  I'd like to create an "app window" for sshcode, but the port needs to stay the same.

finally, is it possible to run this without sshing to a remote server so I can bring up vscode in a browser on my chromebook and it's running in a crouton shell?

this project is very cool!

**Comment by BranLiang** [comment]
would also like to know if we can specify the port number

**Comment by sreya92** [comment]
@jots i'm a little confused by the question regarding not ssh'ing to a remote server, couldn't you just run start up the `code-server` binary locally? 

Regarding the port, they're not exposed right now but it would be very simple to expose them. We could potentially have a `--no-open` flag for not opening up a browser window...would you elaborating on your use case?

**Comment by roberthmiller** [comment]
If this is something that should be implemented, as part of #82, I can include this.

**Comment by sreya92** [comment]
@roberthmiller if you like you could implement it as part of your PR, I'd add a `--local-port` flag

**Comment by sreya92** [comment]
@jots if you run `go get -u go.coder.com/sshcode` you should be able to specify the port with the `--bind` option.

**Comment by roberthmiller** [comment]
@sreya92 #98 is the second part of this issue.
