### ISSUE TITLE
Unable to use sshcode to AWS instance

### ISSUE THREAD

**Issue by randyg3000** [cdr/sshcode#96]
No trouble with the trivial example where I have a pre-shared public key

But when I try this to a remote AWS instance I run into issues with authentication.
The basic ssh connection to AWS works like this:

$ ssh user@*.compute.amazonaws.com -i aws-key-pair.pem
Warning: No xauth data; using fake authentication data for X11 forwarding.
Last login: Tue May  7 23:44:42 2019 from *
[ec2-user@ip-* ~]$

Using sshcode with the same Amazon instance and aws-key-pair.pem fails, per below.

(Note that I had to put the entire argument in quotations to get this far, maybe there is a combination of quoting/escaping that would make this work?)

$ sshcode "user@*.compute.amazonaws.com -i aws-key-pair.pem"
2019-05-07 13:53:27 INFO	ensuring code-server is updated...
Warning: No xauth data; using fake authentication data for X11 forwarding.
+ mkdir -p /home/ec2-user/.local/share/code-server
+ cd /tmp
+ wget -N https://codesrv-ci.cdr.sh/latest-linux
--2019-05-07 23:53:34--  https://codesrv-ci.cdr.sh/latest-linux
Resolving codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)... 104.27.132.26, 104.27.133.26, 2606:4700:30::681b:851a, ...
Connecting to codesrv-ci.cdr.sh (codesrv-ci.cdr.sh)|104.27.132.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Cookie coming from codesrv-ci.cdr.sh attempted to set domain to codesrv-ci.cdr.sh
Length: 94698820 (90M) [application/octet-stream]
Server file no newer than local file ‘latest-linux’ -- not retrieving.

+ '[' -f /tmp/codessh-code-server ']'
+ rm /tmp/codessh-code-server
+ ln latest-linux /tmp/codessh-code-server
+ chmod +x /tmp/codessh-code-server
2019-05-07 13:53:34 INFO	syncing settings
**ssh: Could not resolve hostname *.compute.amazonaws.com -i aws-key-pair.pem: nodename nor servname provided, or not known**
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52.200.1/rsync/io.c(453) [sender=2.6.9]
2019-05-07 13:53:34 FATAL	failed to sync settings: failed to rsync '/Users/***/Library/Application Support/Code/User/' to 'userr@e*.compute.amazonaws.com -i aws-key-pair.pem:.local/share/code-server/User/': exit status 12

**Comment by roberthmiller** [comment]
The host and args should be seperated

**Comment by randyg3000** [comment]
Would you be able to provide a bit more guidance?
since we know

$ ssh user@amazon -i pemfile

works

but i have not come up with a scenario such as

$ sshcode user@amazon --ssh-flags -i pemfile

that works e.g. by not quoting or single/double quotes around "-i pemfile"

**Comment by sreya92** [comment]
Try `sshcode user@amazon --sh-flags="-i pemfile"`

**Comment by randyg3000** [comment]
thanks that got me connected!

**Comment by randyg3000** [comment]
actually, the command that finally worked was

sshcode --ssh-flags "-i aws-key-pair.pem" user@*.amazonaws.com

putting this here for future reference
